title: CSIRKEBUBU'S BLOG
author: akos40
email: akos40@hotmail.hu
description: > # this means to ignore newlines until "baseurl:"
  Hi there! This is my blog about my journey on GitHub as a wannabe developer.
Hope have a great time on here! :dolphin:

# social links
twitter_username: @kovacsakosgergo
github_username:  @akos40

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
